apiVersion: v1
kind: Service
metadata:
  name: rocketmq-svc
spec:
  selector:
    app: rocketmq
  ports:
    - port: 80
      targetPort: 10881
      name: http
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: rocketmq
     annotations:
       name6: value11
    spec:
      containers:
      - name: enotasqueue
        image: jonathansouza23/chrome:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 10881
